### PR TITLE
Update the link to the Firefox protocol

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@AutomatedTester @jgraham, is this the right thing to link to?

**Comment by jgraham** [comment]
This seems to replace a link refering to the WIP implementation of an additional CDP-compatible protocol in Firefox with a link to a description of the current non-CDP-compatible protocol.

**Comment by foolip** [comment]
OK, I wasn't sure what I was looking at, I followed the link from https://remotedebug.org/specifications/ and found the same documentation on GitHub.

Is there a link for the CDP-compatible protocol under development?

**Comment by foolip** [comment]
@digitarald, perhaps you can point to the current documentation for existing Firefox debug protocol, and any future work on something CDP-like, if that is being considered?

**Comment by digitarald** [comment]
@foolip 

> current documentation for existing Firefox debug protocol

The best overview would be https://github.com/mozilla/gecko-dev/blob/master/devtools/docs/backend/protocol.md . We have not invested in any continuous documentation as we don't have API consumers outside of Firefox. Anytime I wanted more details about specific APIs I found the code was the best documentation: https://github.com/mozilla/gecko-dev/tree/master/devtools/server/actors .

> future work on something CDP-like, if that is being considered?

No links here yet. We are investigating `devtools-protocol`'s fit into our roadmap and will follow the discussions, but haven't prioritized anything in the short-term.

**Comment by christian-bromann** [comment]
@foolip I build a nodejs library called [Foxdriver](https://github.com/saucelabs/foxdriver/tree/master/docs) that allows to connect to the devtools interface and all its actors. Check out its [docs](https://github.com/saucelabs/foxdriver/tree/master/docs), it contains most of the interfaces that I found in the code.

**Comment by foolip** [comment]
@christian-bromann, do you have a link to docs for the protocol that Foxdriver uses, something in the Gecko source tree perhaps?

**Comment by christian-bromann** [comment]
> something in the Gecko source tree perhaps?

Yeah, I pretty much adapted it from what I've seen in the gecko code

**Pull request closed without merging**
